Still trying to fix the exit codes with vagrant up

diff --git a/vagrant/guide-common-base/Vagrantfile b/vagrant/guide-common-base/Vagrantfile
--- a/vagrant/guide-common-base/Vagrantfile
+++ b/vagrant/guide-common-base/Vagrantfile
@@ -11,6 +11,7 @@ cd OctopusGuides/vm
 ./common-base.sh
 
 if [[ $? -ne 0 ]]; then
+    echo "Install script failed with $?"
     exit 1
 fi
 
